name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build Website
      run: |
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json"  -H "Content-Type: application/json" https://api.github.com/repos/ruddra/${{ secrets.REPO_NAME}}/dispatches --data '{"event_type": "build_application"}'
